# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'impact_table.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DlgImpact(object):
    def setupUi(self, DlgImpact):
        DlgImpact.setObjectName("DlgImpact")
        DlgImpact.resize(640, 480)
        self.tableWidget = QtWidgets.QTableWidget(DlgImpact)
        self.tableWidget.setGeometry(QtCore.QRect(5, 11, 621, 451))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)

        self.retranslateUi(DlgImpact)
        QtCore.QMetaObject.connectSlotsByName(DlgImpact)

    def retranslateUi(self, DlgImpact):
        _translate = QtCore.QCoreApplication.translate
        DlgImpact.setWindowTitle(_translate("DlgImpact", "Impact Table"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("DlgImpact", "Project"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("DlgImpact", "Type"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("DlgImpact", "Distance"))
